name: WASM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_wasm:
    name: Build Wasm wheels
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  # v6.1.0
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install Cmake
        run: |
          sudo apt-get install -yy cmake

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - name: Build wheels for wasm
        run: python -m cibuildwheel --output-dir pyodide-dist
        env:
          CIBW_PLATFORM: pyodide
          PYODIDE_BUILD_EXPORTS: whole_archive

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: cibw-wheels-wasm
          path: pyodide-dist/*.whl
          if-no-files-found: error

  test_wasm:
    name: Test Wasm wheels
    needs: build_wasm
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        pyodide-version: ["0.27.7", "0.28.2"]
        node-version: ["24.9.0"]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: 3.12

      - uses: pyodide/pyodide-actions/download-pyodide@012fa537869d343726d01863a34b773fc4d96a14 # v2
        with:
          version: ${{ matrix.pyodide-version }}
          to: pyodide-dist

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: cibw-wheels-wasm
          path: pyodide-dist

      - name: Run tests with Pyodide in Node.js
        run: |
          zip -r pyodide-dist/pyodide-home.zip pyproject.toml lib 1> /dev/null
          python -m http.server -d pyodide-dist &
          p=$!; while ! nc -z localhost 8000; do sleep 1; done; echo ready$pid $p$
          cp lib/test/run.mts pyodide-dist/run.mts
          cd pyodide-dist
          node run.mts
